apiVersion: v1
kind: Service
metadata:
  name: mariadb

spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb

spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# NOTE: Use some kind of encryption / external secrets operator in production!
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password

stringData:
  # NOTE: This vulnerable value should not be used in production!
  root-password: "root-password"
  traq-password: "traq-password"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb

spec:
  serviceName: mariadb
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb

      containers:
        - name: mariadb
          image: mariadb:11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: root-password
            - name: MARIADB_USER
              value: traq
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: traq-password
            - name: MARIADB_DATABASE
              value: traq
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
